(() => {
  const form = document.querySelector("#ai-check-form");
  if (!form) return;
  const $ = (selector) => document.querySelector(selector);
  const input = $("#source-input");
  const errorBox = $("#ai-check-error");
  const results = $("#ai-check-results");
  const reportStatus = $("#ai-report-status");
  const MAX_EXAMPLES = 3;

  const track = (name, detail = {}) => {
    if (typeof window.gtag === "function") window.gtag("event", name, { tool: "ai-website-checker", ...detail });
  };
  const el = (tag, className, text) => {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
  };
  const squash = (text) => text.replace(/\s+/g, " ").trim();
  const snippet = (text, index, length, pad = 45) => {
    const start = Math.max(0, index - pad);
    const end = Math.min(text.length, index + length + pad);
    return `${start > 0 ? "..." : ""}${text.slice(start, end).trim()}${end < text.length ? "..." : ""}`;
  };
  // Pick examples far enough apart that their snippets don't repeat the same sentence.
  const spread = (matches) => {
    const picked = [];
    [...matches].sort((a, b) => a.index - b.index).forEach((m) => {
      if (picked.length < MAX_EXAMPLES && (!picked.length || m.index - picked[picked.length - 1].index > 80)) picked.push(m);
    });
    return picked;
  };
  const plural =(count, one, many = `${one}s`) => `${count} ${count === 1 ? one : many}`;

  // Phrases that show up far more in generated marketing copy than in plain business writing.
  const STOCK_PHRASES = [
    "elevate", "seamless", "seamlessly", "unlock", "unleash", "delve", "dive into", "embark", "realm", "tapestry", "testament to",
    "in today's fast-paced", "in today's digital", "digital landscape", "ever-evolving", "ever-changing", "cutting-edge", "state-of-the-art",
    "game-changer", "game changer", "next level", "next-level", "supercharge", "revolutionize", "revolutionise", "transform your",
    "harness the power", "empower", "tailored solutions", "innovative solutions", "bespoke solutions", "one-stop", "look no further",
    "we are passionate", "we're passionate", "passionate about", "at the heart of", "leverage", "synergy", "streamline", "world-class",
    "unparalleled", "effortlessly", "meticulously", "crafted with", "navigate the", "robust", "take your business", "whether you're",
    "whether you are", "your journey", "our journey", "stand out from the crowd", "bring your vision to life", "brings your vision",
    "from concept to", "pixel-perfect", "boost your", "skyrocket", "hassle-free", "we've got you covered"
  ];
  const STOCK_PATTERNS = [
    { label: "\"not just X, it's Y\"", re: /\b(?:not|isn't|is not) just\b[^.!?]{2,60}?\b(?:it's|it is|but|we're|we are)\b/gi }
  ];
  const escapeRe = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/'/g, "['\u2019]");
  const PHRASE_RE = new RegExp(`\\b(?:${STOCK_PHRASES.map(escapeRe).join("|")})\\b`, "gi");

  const PLACEHOLDER_RE = /\b(?:lorem ipsum|dolor sit amet|your company(?: name)?|company name|john doe|jane doe|123 main st(?:reet)?|your@email|your email here|name@example\.com|@example\.com|\(555\)|555-\d{4}|insert (?:text|image|here)|placeholder text|acme (?:inc|corp|co))\b|\[(?:your|insert|company|name)[^\]]{0,30}\]/gi;
  const STAT_RE = /(?<![\d.,])\d+(?:[.,]\d+)*\s?(?:k\+|\+|%|x)(?:\s+[a-z][\w'-]*){1,3}/gi;
  const CLAIM_WORDS_RE = /\b(?:happy|satisfied|clients?|customers?|satisfaction|success|projects?|businesses|companies|brands|growth|faster|increase|revenue|conversions?|reviews?|users|downloads|countries|results|roi|retention)\b/i;
  const EMOJI_RE =/\p{Emoji_Presentation}|\p{Extended_Pictographic}\uFE0F/gu;
  const DEFAULT_TITLE_RE = /^(?:vite \+ react(?: \+ ts)?|vite app|react app|create next app|next\.js app|lovable generated project|my (?:website|app)|untitled|document|home|index|welcome)$/i;
  const DEFAULT_META_RE = /generated by create next app|web site created using create-react-app|lovable generated project/i;
  const STOCK_IMAGE_HOSTS = [
    { re: /(?:i\.pravatar\.cc|randomuser\.me|ui-avatars\.com|api\.dicebear\.com)/i, kind: "avatar" },
    { re: /(?:picsum\.photos|placehold\.co|placeholder\.com|via\.placeholder|dummyimage\.com|placekitten|fakeimg\.pl)/i, kind: "placeholder" },
    { re: /(?:images\.unsplash\.com|source\.unsplash\.com|images\.pexels\.com|pixabay\.com\/get|cdn\.pixabay)/i, kind: "stock" }
  ];
  const BUILDERS = [
    { name: "Lovable", ai: true, test: (s, d) => /gpteng\.co|lovable-uploads|lovable\.dev|lovable-tagger/i.test(s) || /^lovable$/i.test(meta(d, "author")) },
    { name: "Bolt", ai: true, test: (s) => /bolt\.new/i.test(s) },
    { name: "v0", ai: true, test: (s) => /\bv0\.(?:dev|app)\b/i.test(s) },
    { name: "Base44", ai: true, test: (s) => /base44/i.test(s) },
    { name: "Durable", ai: true, test: (s) => /durable\.co\b/i.test(s) },
    { name: "Hostinger Website Builder", ai: true, test: (s) => /zyrosite|zyro\.com|hostinger\.com\/website-builder/i.test(s) },
    { name: "10Web", ai: true, test: (s) => /10web\.(?:io|site)/i.test(s) },
    { name: "Framer", test: (s, d) => /framerusercontent\.com|framer\.(?:website|app)/i.test(s) || /framer/i.test(meta(d, "generator")) },
    { name: "Webflow", test: (s, d) => /data-wf-page|webflow\.(?:com|io)/i.test(s) || /webflow/i.test(meta(d, "generator")) },
    { name: "Wix", test: (s, d) => /static\.wixstatic\.com|wix\.com/i.test(s) || /wix/i.test(meta(d, "generator")) },
    { name: "Squarespace", test: (s) => /squarespace/i.test(s) },
    { name: "Shopify", test: (s) => /cdn\.shopify\.com/i.test(s) },
    { name: "WordPress", test: (s, d) => /wp-content|wp-includes/i.test(s) || /wordpress/i.test(meta(d, "generator")) },
    { name: "Next.js", test: (s) => /\/_next\/static|_NEXT_DATA_/i.test(s) },
    { name: "Tailwind CSS", test: (s) => /class="[^"]*\b(?:flex|grid) [^"]*\b(?:px|py|mx|my|gap)-\d/i.test(s) }
  ];
  const COMMON_FONTS = ["Inter", "Poppins", "Geist", "Space Grotesk", "Plus Jakarta Sans", "Outfit", "DM Sans", "Manrope"];
  const SOCIAL_ROOT_RE = /^https?:\/\/(?:www\.)?(?:twitter|x|facebook|instagram|linkedin|github|youtube|tiktok|dribbble|behance)\.com\/?(?:#.*)?$/i;

  function meta(doc, name) {
    const node = doc && doc.querySelector(`meta[name="${name}" i]`);
    return node ? (node.getAttribute("content") || "").trim() : "";
  }

  const visibleText = (doc) => {
    const body = doc.body ? doc.body.cloneNode(true) : doc.documentElement.cloneNode(true);
    body.querySelectorAll("script, style, noscript, template, svg, iframe").forEach((node) => node.remove());
    body.querySelectorAll("*").forEach((node) => node.append(" "));
    return squash(body.textContent || "");
  };

  const classifyName = (name) => {
    if (/^(?:css|sc|jsx|svelte|emotion|framer|astro|chakra|mui|Mui|_)[-_][\w-]*\d/i.test(name) || /^[a-z]{1,3}-[a-zA-Z0-9]{5,}$/.test(name) && /\d/.test(name) || /^:r\w*:$|^radix-/.test(name)) return "generated";
    if (/[:[\]/.!]/.test(name) || /^-?(?:m|p)[trblxy]?-|^(?:flex|grid|block|inline|hidden|relative|absolute|fixed|sticky|text-|bg-|w-|h-|min-|max-|gap-|space-|rounded|shadow|border|font-|leading-|tracking-|items-|justify-|self-|col-|row-|z-|top-|left-|right-|bottom-|inset-|opacity-|transition|duration-|ease-|overflow|object-|aspect-|container$|sr-only|underline|uppercase|lowercase|italic|truncate|antialiased)/.test(name)) return "utility";
    if (/[a-z0-9]_[a-z0-9]|[a-z0-9]--[a-z0-9]/.test(name) && !/[A-Z]/.test(name)) return "bem";
    if (/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(name)) return name.includes("-") ? "kebab" : "single";
    if (/^[a-z]+[a-z0-9]*[A-Z][A-Za-z0-9]*$/.test(name)) return "camel";
    if (/^[A-Z][A-Za-z0-9]*$/.test(name)) return "pascal";
    if (/^[a-z0-9]+(?:_[a-z0-9]+)+$/.test(name)) return "snake";
    return "other";
  };
  const STYLE_LABELS = { bem: "BEM (block_element)", kebab: "kebab-case", camel: "camelCase", pascal: "PascalCase", snake: "snake_case" };

  const findAll = (re, text) => {
    const out = [];
    re.lastIndex = 0;
    let match;
    while ((match = re.exec(text))) {
      out.push({ text: match[0], index: match.index });
      if (match[0].length === 0) re.lastIndex += 1;
    }
    return out;
  };

  const analyse = (source) => {
    const isHtml = /<\s*(?:!doctype|html|head|body|div|section|main|p|span|h[1-6]|a)\b/i.test(source);
    const doc = isHtml ? new DOMParser().parseFromString(source, "text/html") : null;
    const text = doc ? visibleText(doc) : squash(source);
    const words = text ? text.split(/\s+/).length : 0;
    const per1000 = (count) => (words ? (count / words) * 1000 : 0);
    const findings = [];
    const passed = [];
    const built = [];
    const notices = [];
    const add = (finding) => findings.push(finding);

    // Writing
    const dashes = findAll(/\u2014|\s\u2013\s/g, text);
    if (dashes.length) {
      const heavy = dashes.length >= 8 || per1000(dashes.length) >= 3;
      add({ area: "Writing", level: heavy ? "medium" : "low", points: heavy ? 12 : 5, title: `${plural(dashes.length, "em dash", "em dashes")} in the copy`, why: "The character is correct punctuation, but many readers now associate frequent em dashes with ChatGPT-style writing.", fix: "Split the sentence in two, or use a comma, colon or a plain hyphen with spaces.", examples: spread(dashes).map((m) => snippet(text, m.index, m.text.length, 35)) });
    } else if (words > 40) passed.push("No em dashes in the copy");

    const phraseHits = findAll(PHRASE_RE, text);
    STOCK_PATTERNS.forEach((pattern) => findAll(pattern.re, text).forEach((m) => phraseHits.push({ ...m, label: pattern.label })));
    if (phraseHits.length) {
      const counts = new Map();
      phraseHits.forEach((m) => { const key = m.label || m.text.toLowerCase(); counts.set(key, (counts.get(key) || 0) + 1); });
      const rate = per1000(phraseHits.length);
      const level = phraseHits.length >= 8 || rate >= 8 ? "high" : phraseHits.length >= 3 || rate >= 3 ? "medium" : "low";
      const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([p, c]) => (c > 1 ? `${p} (${c})` : p));
      add({ area: "Writing", level, points: { high: 22, medium: 12, low: 4 }[level], title: `${plural(phraseHits.length, "stock phrase")} common in generated copy`, why: `Found: ${top.join(", ")}. Phrases like these could describe any business, so they tell visitors nothing about yours.`, fix: "Replace each one with a specific fact: who you work with, where, what you delivered and what changed.", examples: spread(phraseHits).map((m) => snippet(text, m.index, m.text.length, 35)) });
    } else if (words > 40) passed.push("No stock marketing phrases found");

    const placeholders = findAll(PLACEHOLDER_RE, doc ? `${text} ${[...doc.querySelectorAll("a[href^='mailto:'], a[href^='tel:']")].map((a) => a.getAttribute("href")).join(" ")}` : text);
    if (placeholders.length) {
      add({ area: "Writing", level: "high", points: 25, title: `Placeholder text left on the page (${placeholders.length})`, why: "Template text such as lorem ipsum, example emails or \"Your Company\" tells visitors the site was never finished or checked.", fix: "Replace every placeholder with real content, or remove the section until it's ready.", examples: [...new Set(placeholders.map((m) => m.text))].slice(0, MAX_EXAMPLES) });
    } else if (words > 20) passed.push("No placeholder text");

    // Small numbers ("4+ years") are ordinary facts; round marketing claims are what visitors discount.
    const stats = findAll(STAT_RE, text).filter((m) => (/%|x\b|k\+/i.test(m.text) || parseFloat(m.text.replace(/,/g, "")) >= 20) && CLAIM_WORDS_RE.test(m.text));
    if (stats.length >= 2) {
      add({ area: "Writing", level: stats.length >= 4 ? "medium" : "low", points: stats.length >= 4 ? 8 : 3, title: `${plural(stats.length, "unsourced headline number")}`, why: "Round claims like \"500+ happy clients\" or \"99% satisfaction\" are a staple of generated landing pages, and visitors discount them unless they can see where they come from.", fix: "Keep numbers you can back up and say where they come from, or replace them with one named project.", examples: stats.slice(0, MAX_EXAMPLES).map((m) => m.text.trim()) });
    }

    // Design defaults and leftovers (HTML only)
    if (doc) {
      const emojiNodes = [...doc.querySelectorAll("h1, h2, h3, h4, button, a, li")].filter((node) => { EMOJI_RE.lastIndex = 0; return EMOJI_RE.test(node.textContent); });
      if (emojiNodes.length) {
        add({ area: "Design", level: emojiNodes.length >= 4 ? "medium" : "low", points: emojiNodes.length >= 4 ? 8 : 3, title: `Emoji in ${plural(emojiNodes.length, "heading, button or list item", "headings, buttons or list items")}`, why: "Emoji used as icons and bullet points (rockets, sparkles, check marks) are a common default in generated pages.", fix: "Use a consistent icon set or plain text. Keep emoji for places your brand really uses them.", examples: emojiNodes.slice(0, MAX_EXAMPLES).map((node) => squash(node.textContent).slice(0, 80)) });
      }

      const classBlob = [...doc.querySelectorAll("[class]")].map((node) => node.getAttribute("class")).join(" ");
      const styleBlob = [...doc.querySelectorAll("style")].map((node) => node.textContent).join(" ") + [...doc.querySelectorAll("[style]")].map((node) => node.getAttribute("style")).join(" ");
      const gradientText = /\bbg-clip-text\b/.test(classBlob) && /\btext-transparent\b/.test(classBlob) || /background-clip:\s*text/i.test(styleBlob);
      const purpleGradient = /\b(?:from|via|to)-(?:purple|violet|indigo|fuchsia|pink)-\d{2,3}\b/.test(classBlob);
      if (gradientText || purpleGradient) {
        const both = gradientText && purpleGradient;
        add({ area: "Design", level: both ? "medium" : "low", points: both ? 10 : 4, title: both ? "Purple gradient headline text" : gradientText ? "Gradient headline text" : "Purple and blue gradients", why: "Gradient text and purple-to-blue gradients are among the most recognisable defaults of AI-built and template sites.", fix: "Use your brand colours, and let photography or real work carry the visual interest.", examples: [] });
      }
      if (/\bbackdrop-blur(?:-\w+)?\b/.test(classBlob) && /\bblur-(?:2xl|3xl)\b/.test(classBlob)) {
        add({ area: "Design", level: "low", points: 3, title: "Blurred background blobs and glass cards", why: "Glass panels over blurred colour blobs are another very common generated-page default.", fix: "Fine in moderation. Make sure it's a design choice rather than a leftover.", examples: [] });
      }

      const fontSource = `${styleBlob} ${[...doc.querySelectorAll("link[href*='fonts']")].map((node) => node.getAttribute("href")).join(" ")} ${classBlob}`;
      const fonts = COMMON_FONTS.filter((font) => new RegExp(`${font.replace(/ /g, "[ +]")}\\b`, "i").test(fontSource) || new RegExp(`\\bfont-${font.toLowerCase().replace(/ /g, "-")}\\b`).test(classBlob));
      if (fonts.length) {
        add({ area: "Design", level: "low", points: 2, title: `Very common font choice: ${fonts.join(", ")}`, why: "Good fonts, and not a problem on their own. They are the default in so many generated and template sites that they don't help you stand out.", fix: "Optional. If the site feels generic overall, a distinctive heading font is an easy change.", examples: [] });
      }

      const images = [...doc.querySelectorAll("img[src], source[srcset], img[srcset]")].map((node) => node.getAttribute("src") || node.getAttribute("srcset") || "");
      const bgImages = (styleBlob.match(/url\(([^)]+)\)/g) || []);
      const imageRefs = [...images, ...bgImages];
      const hostHits = { avatar: [], placeholder: [], stock: [] };
      imageRefs.forEach((ref) => STOCK_IMAGE_HOSTS.forEach((host) => { if (host.re.test(ref)) hostHits[host.kind].push(ref); }));
      if (hostHits.avatar.length || hostHits.placeholder.length) {
        const all = [...hostHits.avatar, ...hostHits.placeholder];
        add({ area: "Images", level: "high", points: 16, title: `${plural(all.length, "placeholder or generated avatar image")}`, why: "Random avatar and placeholder services are what generators use for testimonials and team photos. Visitors who notice will doubt the people are real.", fix: "Use real photos with permission, or remove the photo and keep a named quote with company and role.", examples: all.slice(0, MAX_EXAMPLES) });
      } else if (imageRefs.length) passed.push("No placeholder or random avatar images");
      if (hostHits.stock.length) {
        add({ area: "Images", level: hostHits.stock.length >= 3 ? "medium" : "low", points: hostHits.stock.length >= 3 ? 7 : 3, title: `${plural(hostHits.stock.length, "stock photo")} loaded from Unsplash or Pexels`, why: "Free stock images appear on thousands of sites, and generators pull them in by default.", fix: "Use photos of your actual team, workplace, products or projects wherever you can.", examples: hostHits.stock.slice(0, MAX_EXAMPLES).map((ref) => ref.slice(0, 90)) });
      }

      // Code leftovers
      const title = doc.title ? doc.title.trim() : "";
      const description = meta(doc, "description");
      if (DEFAULT_TITLE_RE.test(title) || DEFAULT_META_RE.test(description) || DEFAULT_META_RE.test(title)) {
        add({ area: "Code", level: "high", points: 18, title: "Template default title or description", why: "The page title or description still says what the starter template set, and that's what Google shows in search results.", fix: "Write a title and description that name your business and what the page offers.", examples: [title && `<title>${title}</title>`, description && `description: ${description}`].filter(Boolean) });
      }

      const comments = [];
      const walker = doc.createTreeWalker(doc, NodeFilter.SHOW_COMMENT);
      while (walker.nextNode()) comments.push(squash(walker.currentNode.nodeValue));
      const todoComments = comments.filter((c) => /\b(?:replace (?:this|with)|add (?:your|more)|your (?:content|logo|image) here|todo|fixme|example content|dummy)\b/i.test(c));
      const sectionComments = comments.filter((c) => /^(?:hero|features?|testimonials?|pricing|cta|call to action|footer|header|navbar|navigation|about(?: us)?|services|contact|faq|stats|team)(?: section)?$/i.test(c) || /\bsection\b/i.test(c) && c.length < 40);
      if (todoComments.length) {
        add({ area: "Code", level: "medium", points: 8, title: `${plural(todoComments.length, "unfinished instruction", "unfinished instructions")} left in code comments`, why: "Comments like \"Replace with your image\" are copied straight from generated code and are visible to anyone who views the source.", fix: "Remove them, and check the part of the page they refer to was actually finished.", examples: todoComments.slice(0, MAX_EXAMPLES).map((c) => `<!-- ${c.slice(0, 80)} -->`) });
      }
      if (sectionComments.length >= 3) {
        add({ area: "Code", level: "low", points: 3, title: `${plural(sectionComments.length, "section-label comment")} such as <!-- Hero Section -->`, why: "Harmless, but typical of code pasted from a chat assistant.", fix: "Optional. Remove them, or keep them if your team finds them useful.", examples: sectionComments.slice(0, MAX_EXAMPLES).map((c) => `<!-- ${c} -->`) });
      }

      const links = [...doc.querySelectorAll("a[href]")];
      const deadLinks = links.filter((a) => /^(?:#|javascript:void\(0\);?)$/i.test(a.getAttribute("href").trim()));
      const socialRoots = links.filter((a) => SOCIAL_ROOT_RE.test(a.getAttribute("href").trim()));
      if (socialRoots.length) {
        add({ area: "Code", level: "high", points: 14, title: `${plural(socialRoots.length, "social link")} pointing at the platform, not a profile`, why: "Links to twitter.com or facebook.com with no profile are template defaults. Visitors who click them land nowhere.", fix: "Link to your actual profiles, or remove the icons for platforms you don't use.", examples: socialRoots.slice(0, MAX_EXAMPLES).map((a) => a.getAttribute("href")) });
      }
      if (deadLinks.length) {
        add({ area: "Code", level: deadLinks.length >= 3 ? "medium" : "low", points: deadLinks.length >= 3 ? 9 : 3, title: `${plural(deadLinks.length, "link")} that go${deadLinks.length === 1 ? "es" : ""} nowhere (href="#")`, why: "Menu items, buttons and footer links that don't lead anywhere are a sign of an unfinished template.", fix: "Point each one at a real page, or use a button element if it opens something on the same page.", examples: deadLinks.slice(0, MAX_EXAMPLES).map((a) => `${squash(a.textContent).slice(0, 40) || "(no text)"} -> ${a.getAttribute("href")}`) });
      } else if (links.length) passed.push("Every link has a destination");

      // Naming consistency
      const names = [];
      doc.querySelectorAll("[class]").forEach((node) => node.getAttribute("class").split(/\s+/).filter(Boolean).forEach((name) => names.push(name)));
      doc.querySelectorAll("[id]").forEach((node) => names.push(node.id));
      const unique = [...new Set(names)];
      const styles = {};
      unique.forEach((name) => { const style = classifyName(name); (styles[style] ||= []).push(name); });
      const conventionCounts = Object.entries(STYLE_LABELS).map(([key, label]) => [key, label, (styles[key] || []).length]).filter(([, , count]) => count > 0);
      const semanticTotal = conventionCounts.reduce((sum, [, , count]) => sum + count, 0);
      const hyphenFamily = (styles.bem || []).length + (styles.kebab || []).length;
      const otherFamilies = conventionCounts.filter(([key]) => key !== "bem" && key !== "kebab");
      const otherTotal = otherFamilies.reduce((sum, [, , count]) => sum + count, 0);
      const minority = Math.min(hyphenFamily, otherTotal) + (otherFamilies.length > 1 ? Math.min(...otherFamilies.map(([, , c]) => c)) : 0);
      if (semanticTotal >= 8 && minority >= 3 && minority / semanticTotal >= 0.1) {
        add({ area: "Code", level: "low", points: 4, title: "Class and ID names mix naming styles", why: `Found ${conventionCounts.map(([, label, count]) => `${count} ${label}`).join(", ")}. Visitors never see this and Google does not rank on it, but mixed conventions make the code harder to maintain.`, fix: "Pick one convention (kebab-case is the most common for HTML and CSS) and rename the rest when you next work on the page.", examples: otherFamilies.flatMap(([key]) => styles[key].slice(0, 2)).concat((styles.kebab || []).slice(0, 1)).slice(0, MAX_EXAMPLES) });
      } else if (semanticTotal >= 8) passed.push("Class and ID names follow a consistent style");

      const idCounts = new Map();
      doc.querySelectorAll("[id]").forEach((node) => idCounts.set(node.id, (idCounts.get(node.id) || 0) + 1));
      const duplicateIds = [...idCounts.entries()].filter(([id, count]) => id && count > 1);
      if (duplicateIds.length) {
        add({ area: "Code", level: "medium", points: 6, title: `${plural(duplicateIds.length, "duplicate ID")}`, why: "An ID must be unique on a page. Duplicates break links to page sections, form labels and scripts, and often come from copying generated blocks.", fix: "Give each element its own ID, or switch to a class if the style is shared.", examples: duplicateIds.slice(0, MAX_EXAMPLES).map(([id, count]) => `id="${id}" used ${count} times`) });
      } else if (idCounts.size) passed.push("No duplicate IDs");

      // Trust and search basics
      if (!title || !description) {
        add({ area: "Search", level: "medium", points: 6, title: !title && !description ? "No page title or meta description" : !title ? "No page title" : "No meta description", why: "The title and description are what people see in Google results before they decide to click.", fix: "Add a specific title (under about 60 characters) and a one or two sentence description.", examples: [] });
      } else if (!DEFAULT_TITLE_RE.test(title)) passed.push("Page title and description are set");
      const h1s = doc.querySelectorAll("h1").length;
      if (h1s !== 1 && words > 40) {
        add({ area: "Search", level: "low", points: 3, title: h1s ? `${h1s} main headings (h1) on one page` : "No main heading (h1)", why: "One clear main heading helps visitors and search engines understand what the page is about.", fix: "Use a single h1 that says what the page offers, and h2 and h3 for sections.", examples: [] });
      }
      const contact = doc.querySelector("a[href^='mailto:'], a[href^='tel:'], form, a[href*='contact' i]");
      if (!contact && words > 80) {
        add({ area: "Trust", level: "medium", points: 7, title: "No obvious way to get in touch", why: "No email link, phone link, form or contact page was found. Visitors deciding whether to trust you look for a real way to reach a person.", fix: "Add a visible email address, phone number or contact form with a named person where possible.", examples: [] });
      } else if (contact) passed.push("Visitors can find a way to get in touch");
      const yearMatch = text.match(/(?:©|&copy;|copyright)\s*(?:\d{4}\s*[-\u2013]\s*)?(\d{4})/i);
      const thisYear = new Date().getFullYear();
      if (yearMatch && Number(yearMatch[1]) < thisYear - 1) {
        add({ area: "Trust", level: "low", points: 3, title: `Footer copyright says ${yearMatch[1]}`, why: "An old year suggests nobody is looking after the site.", fix: "Update it, or set it automatically.", examples: [yearMatch[0]] });
      }
      if (doc.querySelector("script[type='application/ld+json']")) passed.push("Structured data is present");

      BUILDERS.forEach((builder) => { if (builder.test(source, doc)) built.push(builder); });
      const aiBuilders = built.filter((b) => b.ai);
      if (aiBuilders.length) {
        add({ area: "Code", level: "medium", points: 8, title: `Built with ${aiBuilders.map((b) => b.name).join(" and ")}, an AI website builder`, why: "Using an AI builder is fine. Its fingerprints are visible in the page source, so the rest of the site needs to feel specific to you.", fix: "Replace default sections, images and copy, and remove any \"made with\" badges you didn't choose to keep.", examples: [] });
      }

      const appRoot = doc.querySelector("#root, #_next, #app, #_nuxt, [data-reactroot]");
      if (words < 60 && (appRoot || doc.querySelector("script[type='module']"))) {
        notices.push("This page builds its content with JavaScript, so the source you pasted contains very little text. For a complete check, open the page, press F12, right-click the <html> element in the Elements panel, choose Copy > Copy outerHTML (or Copy element), and paste that instead.");
      }
    } else {
      notices.push("This looks like plain text rather than page source, so only the writing checks were run. Paste the full page source to also check code, images and links.");
    }
    const hasRenderNotice = notices.some((n) => n.startsWith("This page builds"));
    if (words < 40 && !hasRenderNotice) notices.push(`Only ${plural(words, "word")} of visible text ${words === 1 ? "was" : "were"} found, so the writing checks have little to go on.`);

    const rank = { high: 3, medium: 2, low: 1 };
    findings.sort((a, b) => rank[b.level] - rank[a.level] || b.points - a.points);
    const score = Math.min(100, findings.reduce((sum, f) => sum + f.points, 0));
    const band = score >= 40 ? "poor" : score >= 15 ? "average" : "good";
    const headline = { poor: "This page is likely to read as generic or AI-made.", average: "Some generic patterns stand out.", good: "This page reads as specific to a real business." }[band];
    const high = findings.filter((f) => f.level === "high").length;
    const lead = findings.length
      ? `${plural(findings.length, "pattern")} found${high ? `, ${high} of them worth fixing first` : ""}. ${band === "good" ? "Nothing here should put a visitor off." : "Start at the top of the list."}`
      : "No common generated-site patterns were found in what you pasted.";
    const firstTitle = doc && doc.title ? doc.title.trim() : "";
    return { isHtml, words, findings, passed, built, notices, score, band, headline, lead, pageTitle: firstTitle, checkedAt: new Date() };
  };

  let report = null;
  const LEVEL_TONE = { high: "poor", medium: "average", low: "good" };
  const LEVEL_TEXT = { high: "Fix first", medium: "Worth fixing", low: "Minor" };

  const render = (r) => {
    $("#ai-result-meta").textContent = `${r.isHtml ? "Page source" : "Text"} / ${plural(r.words, "word")}${r.pageTitle ? ` / ${r.pageTitle.slice(0, 60)}` : ""}`;
    $("#ai-result-title").textContent = r.headline;
    $("#ai-result-lead").textContent = r.lead;
    const meter = $("#ai-meter");
    meter.className = `ai-meter is-${r.band}`;
    $("#ai-meter-value").textContent = String(r.score);
    $("#ai-meter-fill").style.left = `${r.score}%`;
    meter.setAttribute("aria-label", `Generic-pattern score ${r.score} out of 100`);

    $("#ai-notice-block").hidden = !r.notices.length;
    $("#ai-notice").textContent = r.notices.join(" ");

    $("#ai-issues-intro").textContent = r.findings.length ? "Most important first. Each finding says why it matters and what to change." : "Nothing to flag. Read the page aloud once anyway: if a sentence could describe any business, make it specific.";
    $("#ai-issue-list").replaceChildren(...r.findings.map((f) => {
      const item = el("li", `issue-item is-${LEVEL_TONE[f.level]}`);
      const body = el("div");
      const metaLine = el("p", "issue-meta");
      metaLine.append(el("span", "issue-impact", LEVEL_TEXT[f.level]), el("span", "", f.area));
      body.append(metaLine, el("h4", "", f.title), el("p", "", f.why));
      if (f.examples.length) {
        const list = el("ul", "issue-examples");
        f.examples.forEach((example) => list.append(el("li", "", example)));
        body.append(list);
      }
      const fix = el("p", "issue-fix");
      fix.append(el("strong", "", "What to do: "), document.createTextNode(f.fix));
      body.append(fix);
      item.append(body);
      return item;
    }));

    $("#ai-built-block").hidden = !r.built.length;
    $("#ai-built-list").replaceChildren(...r.built.map((b) => el("li", "", b.ai ? `${b.name} (AI website builder)` : b.name)));
    $("#ai-passed-block").hidden = !r.passed.length;
    $("#ai-passed-list").replaceChildren(...r.passed.map((label) => el("li", "", label)));
  };

  const reportText = (r) => {
    const lines = [
      "AI WEBSITE CHECK",
      `${r.pageTitle ? `${r.pageTitle}\n` : ""}Checked ${r.checkedAt.toLocaleString("en-GB", { dateStyle: "long", timeStyle: "short" })}, ${plural(r.words, "word")} of visible text`,
      "",
      `Generic-pattern score: ${r.score} / 100`,
      r.headline,
      r.lead
    ];
    if (r.notices.length) lines.push("", `Note: ${r.notices.join(" ")}`);
    lines.push("", "WHAT STOOD OUT");
    if (r.findings.length) {
      r.findings.forEach((f, i) => {
        lines.push(`  ${i + 1}. [${LEVEL_TEXT[f.level].toUpperCase()}] ${f.title} (${f.area})`, `     ${f.why}`);
        f.examples.forEach((example) => lines.push(`     > ${example}`));
        lines.push(`     What to do: ${f.fix}`);
      });
    } else lines.push("  Nothing flagged");
    if (r.built.length) lines.push("", "BUILT WITH", ...r.built.map((b) => `  - ${b.name}${b.ai ? " (AI website builder)" : ""}`));
    if (r.passed.length) lines.push("", "ALREADY IN GOOD SHAPE", ...r.passed.map((p) => `  - ${p}`));
    lines.push("", "This check looks for patterns, it cannot prove how a site was made.", "https://hasnainqureshi.online/tools/ai-website-checker/");
    return lines.join("\n");
  };

  const runCheck = () => {
    const source = input.value;
    errorBox.hidden = true;
    if (source.trim().length < 20) {
      errorBox.textContent = "Paste your page source or some page text first.";
      errorBox.hidden = false;
      input.focus();
      return;
    }
    report = analyse(source);
    render(report);
    results.hidden = false;
    results.focus();
    track("ai_check_run", { input_type: report.isHtml ? "html" : "text", score: report.score, finding_count: report.findings.length });
  };

  form.addEventListener("submit", (event) => { event.preventDefault(); runCheck(); });

  $("#source-file").addEventListener("change", (event) => {
    const file = event.target.files && event.target.files[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) {
      errorBox.textContent = "That file is larger than 5 MB. Upload a single HTML page.";
      errorBox.hidden = false;
      return;
    }
    const reader = new FileReader();
    reader.onload = () => { input.value = String(reader.result || ""); $("#source-meta").textContent = `Loaded ${file.name}. Nothing is uploaded or stored.`; runCheck(); };
    reader.readAsText(file);
    event.target.value = "";
  });

  const EXAMPLE = `<!doctype html>
<html lang="en">
<head>
  <title>Vite + React + TS</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
</head>
<body class="font-sans antialiased">
  <!-- Hero Section -->
  <section class="heroSection min-h-screen flex items-center">
    <h1 class="text-6xl font-bold bg-gradient-to-r from-purple-600 to-blue-500 bg-clip-text text-transparent">Elevate Your Business \u2014 Seamlessly \u{1F680}</h1>
    <p>In today's fast-paced digital landscape, we deliver cutting-edge, tailored solutions that empower you to unlock your full potential. It's not just a website, it's your digital journey.</p>
    <a href="#" class="cta_button">Get Started \u2728</a>
  </section>
  <!-- Stats Section -->
  <section class="stats-grid">
    <p>500+ happy clients</p><p>99% satisfaction rate</p><p>10x faster growth</p>
  </section>
  <!-- Testimonials Section -->
  <section class="testimonials">
    <img src="https://i.pravatar.cc/150?img=5" alt="">
    <p>"Working with them was a game-changer." \u2014 Sarah Johnson, CEO</p>
    <!-- Replace with your real testimonials -->
  </section>
  <footer class="site_footer">
    <a href="https://twitter.com">Twitter</a> <a href="https://facebook.com/">Facebook</a> <a href="#">Privacy</a>
    <p>\u00A9 2023 Your Company. Contact: hello@example.com</p>
  </footer>
</body>
</html>`;

  $("#source-example").addEventListener("click", () => {
    input.value = EXAMPLE;
    $("#source-meta").textContent = "Loaded a made-up example page. Replace it with your own source to check your site.";
    runCheck();
    track("ai_check_example");
  });

  $("#ai-report-copy").addEventListener("click", async () => {
    if (!report) return;
    try { await navigator.clipboard.writeText(reportText(report)); reportStatus.textContent = "Report copied."; } catch { reportStatus.textContent = "Copying is blocked in this browser. Use Download instead."; }
    track("report_copy");
  });

  $("#ai-report-download").addEventListener("click", () => {
    if (!report) return;
    const blob = new Blob([reportText(report)], { type: "text/plain;charset=utf-8" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "ai-website-check.txt";
    document.body.append(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(link.href), 1000);
    reportStatus.textContent = "Report downloaded.";
    track("report_download");
  });

  // Optional rework request
  const sendForm = $("#rewrite-request-form");
  const sendStatus = $("#rewrite-request-status");
  document.querySelectorAll('a[href="#rewrite-request"]').forEach((link) => link.addEventListener("click", () => track("contact_click", { method: "rewrite-request-link" })));
  let sending = false;
  sendForm.addEventListener("submit", async (event) => {
    event.preventDefault();
    if (sending) return;
    if (!sendForm.checkValidity()) { sendForm.reportValidity(); return; }
    sending = true;
    const button = sendForm.querySelector('button[type="submit"]');
    button.disabled = true;
    sendForm.setAttribute("aria-busy", "true");
    $("#rewrite-request-report").value = report ? reportText(report) : "No check run";
    sendStatus.textContent = "Sending...";
    try {
      const response = await fetch(sendForm.action, { method: "POST", body: new FormData(sendForm), headers: { Accept: "application/json" } });
      if (!response.ok) throw new Error("Submission failed");
      sendForm.reset();
      sendStatus.textContent = "Thank you. Your message has been sent. I'll reply by email.";
      track("generate_lead", { method: "ai-checker-form", has_report: Boolean(report) });
    } catch {
      sendStatus.replaceChildren(document.createTextNode("This could not be sent. Your details are still here. Try again, or "));
      const email = el("a", "", "email Hasnain directly");
      email.href = "mailto:husnainqureshi134@gmail.com?subject=AI%20website%20check";
      sendStatus.append(email, document.createTextNode("."));
    } finally {
      sending = false;
      button.disabled = false;
      sendForm.removeAttribute("aria-busy");
    }
  });
})();
